# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f16ce1efce9b3d6bed687e92f9a8b422b743a96960f6b1f00d4abac5bcdfca1c6d627010cadc578fa953d6aed31140b2159008db3bcde7118797a6b8ef903f54

test:
  secret_key_base: 77b4e32f1b721f9e1ec6d3e756dd5100ecce298ba98a2990fbbf35d31b0c829f5e08d79672136d419ceebb6fa8a705c088d686cccc9c9a61af962f5bf3e4beea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
